baseurl = "https://bookbreakdowns.com"
languageCode = "en"
title = "Book Breakdowns"
theme = "current-theme"
copyright = "&copy; <a href=\"https://github.com/beli3ver\">Malte Kiefer</a> 2016"
disqusShortname = "shortname"
googleAnalytics = ""
keywords = ["keyword1", "keyword2"]

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
    url = ""
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post"
    name = "Posts"
    weight = 2

[params]

subtitle = "todo"
description = "It's Kinda Like Cliffs Notes For Your Career! Self-help books broken down into a single blog post. Short and to the point."

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/beli3ver"
fa_icon = "fa-github"

[[params.social]]
url = "https://gitlab.com/beli3ver"
fa_icon = "fa-gitlab"

[[params.social]]
url = "https://twitter.com/malkie16"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://telegram.me/beli3ver"
fa_icon = "fa-telegram"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

pluralizeListTitles = true
